export const FETCH_QUIZZES_START = 'FETCH_QUIZZES_START';
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR';

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const QUIZ_FINISHED = 'QUIZ_FINISHED';
export const QUIZ_REPEAT = 'QUIZ_REPEAT';

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const RESET_CREATE_FORM = 'RESET_CREATE_FORM';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
